In [3]:
import workspace as wp
sta_arab_lan = '''24°42'48.960"N'''
sta_arab_long = '''46°40'31.080"E'''
epi_lan = '''8°33'01.12" S'''
epi_long = '''112°13'24.18" E'''

run=wp.calculate_distance(epi_lan,epi_long,sta_arab_lan,sta_arab_long)
run.create_map()
run.collect_results()

,Titik,Latitude,Longitude,Tan Geografis Lats,Geografis Lats,A,B,C
0,Episenter,-8.550306,112.223361,-0.149338,-8.493663,-0.37407,0.915563,-0.147700
1,Stasiun,24.713600,46.675300,0.457142,24.567133,0.62402,0.624020,0.415759

   Azimut Sin  Azimut cos  Azimut Real  Back Azimut
0  -60.584094   60.584094   299.415906   119.415906

   Cos Delta      Delta   Delta (km)
0   0.310922  71.885188  7987.163261

In [4]:
sta_riyadh_lan = '''24°42'48.96"N'''
sta_riyadh_long = '''46°40'31.08"E'''
epi_tokyo_lan = '''33°35'21" N'''
epi_tokyo_long = '''130°23'59" E'''

run=wp.calculate_distance(epi_tokyo_lan,epi_tokyo_long,sta_riyadh_lan,sta_riyadh_long)
run.create_map()
run.collect_results()

,Titik,Latitude,Longitude,Tan Geografis Lats,Geografis Lats,A,B,C
0,Episenter,33.583889,130.384722,0.659529,33.406015,-0.540875,0.635869,0.550568
1,Stasiun,24.713583,46.675278,0.457142,24.567117,0.624020,0.624020,0.415759

   Azimut Sin  Azimut cos  Azimut Real  Back Azimut
0  -72.087221   72.087221   252.087221    72.087221

   Cos Delta      Delta   Delta (km)
0   0.312092  71.814659  7979.326791